In [3]:
import pandas as pd

In [29]:
data_pursuits = pd.read_csv('data-processed/goal_pursuits.csv')
data_selections = pd.read_csv('data-processed/goal_selections.csv')
data_debrief = pd.read_csv('data-processed/debrief.csv')
selected_goals = pd.read_csv('data-processed/selected_goals.csv')

In [28]:
data_pursuits.head(15)

,timestamp,actor_position,recipient_position,feature,step_number,state_0_type,state_0_shade,state_0_texture,state_1_type,state_1_shade,...,goal_1_shade,goal_1_texture,goal_2_type,goal_2_shade,goal_2_texture,participant_id,trial_number,abandoned,goal_achieved,steps
0,1740261561258,1,0,shape,1,star,light,dots,square,medium,...,medium,plain,square,medium,plain,xoblqmxr2y5olc3ovrzoaufg,1,False,True,6
1,1740261567124,1,0,shape,2,star,light,dots,square,medium,...,medium,plain,square,medium,plain,xoblqmxr2y5olc3ovrzoaufg,1,False,True,6
2,1740261569158,0,2,shape,3,square,light,dots,square,medium,...,medium,plain,square,medium,plain,xoblqmxr2y5olc3ovrzoaufg,1,False,True,6
3,1740261572207,2,0,texture,4,square,light,dots,square,medium,...,medium,plain,square,medium,plain,xoblqmxr2y5olc3ovrzoaufg,1,False,True,6
4,1740261573826,0,1,texture,5,square,light,plain,square,medium,...,medium,plain,square,medium,plain,xoblqmxr2y5olc3ovrzoaufg,1,False,True,6
5,1740261576775,2,0,color,6,square,light,plain,square,medium,...,medium,plain,square,medium,plain,xoblqmxr2y5olc3ovrzoaufg,1,False,True,6
6,1740261590843,0,2,shape,1,cloud,dark,stripes,square,medium,...,medium,stripes,star,medium,stripes,xoblqmxr2y5olc3ovrzoaufg,2,False,True,6
7,1740261592523,2,1,shape,2,cloud,dark,stripes,square,medium,...,medium,stripes,star,medium,stripes,xoblqmxr2y5olc3ovrzoaufg,2,False,True,6
8,1740261594366,1,0,shape,3,cloud,dark,stripes,star,medium,...,medium,stripes,star,medium,stripes,xoblqmxr2y5olc3ovrzoaufg,2,False,True,6
9,1740261595998,0,2,shape,4,star,dark,stripes,star,medium,...,medium,stripes,star,medium,stripes,xoblqmxr2y5olc3ovrzoaufg,2,False,True,6
10,1740261600751,1,0,color,5,star,dark,stripes,star,medium,...,medium,stripes,star,medium,stripes,xoblqmxr2y5olc3ovrzoaufg,2,False,True,6
11,1740261603059,1,2,color,6,star,medium,stripes,star,medium,...,medium,stripes,star,medium,stripes,xoblqmxr2y5olc3ovrzoaufg,2,False,True,6
12,1740261629718,0,1,shape,1,cloud,medium,stripes,square,light,...,medium,plain,cloud,medium,plain,xoblqmxr2y5olc3ovrzoaufg,3,False,True,9
13,1740261631491,0,1,shape,2,cloud,medium,stripes,square,light,...,medium,plain,cloud,medium,plain,xoblqmxr2y5olc3ovrzoaufg,3,False,True,9
14,1740261633168,1,2,shape,3,cloud,medium,stripes,cloud,light,...,medium,plain,cloud,medium,plain,xoblqmxr2y5olc3ovrzoaufg,3,False,True,9

In [30]:
selected_goals

,participant_id,trial_number,abandoned,goal_achieved,shape_0_type,shape_0_shade,shape_0_texture,shape_1_type,shape_1_shade,shape_1_texture,shape_2_type,shape_2_shade,shape_2_texture
0,xoblqmxr2y5olc3ovrzoaufg,1,False,True,square,medium,plain,square,medium,plain,square,medium,plain
1,xoblqmxr2y5olc3ovrzoaufg,2,False,True,star,medium,stripes,star,medium,stripes,star,medium,stripes
2,xoblqmxr2y5olc3ovrzoaufg,3,False,True,cloud,medium,plain,cloud,medium,plain,cloud,medium,plain
3,xoblqmxr2y5olc3ovrzoaufg,4,False,True,square,medium,dots,square,medium,dots,square,medium,dots
4,xoblqmxr2y5olc3ovrzoaufg,5,False,True,cloud,medium,dots,cloud,medium,dots,cloud,medium,dots
5,lhyr2v0802r5eml5u0y2k1g8,1,False,True,cloud,medium,plain,cloud,medium,plain,cloud,medium,plain
6,lhyr2v0802r5eml5u0y2k1g8,2,False,True,square,medium,stripes,square,medium,stripes,square,medium,stripes
7,lhyr2v0802r5eml5u0y2k1g8,3,False,True,star,medium,plain,star,medium,plain,star,medium,plain
8,lhyr2v0802r5eml5u0y2k1g8,4,False,True,star,medium,stripes,star,medium,stripes,star,medium,stripes
9,lhyr2v0802r5eml5u0y2k1g8,5,False,True,star,light,plain,star,light,plain,star,light,dots
10,jsh0wz9edlxszscd891dk534,1,False,True,star,dark,stripes,cloud,medium,plain,cloud,dark,plain
11,jsh0wz9edlxszscd891dk534,2,False,True,cloud,light,dots,square,light,dots,star,light,dots
12,jsh0wz9edlxszscd891dk534,3,False,True,square,medium,plain,square,medium,plain,square,medium,plain
13,jsh0wz9edlxszscd891dk534,4,False,True,square,medium,stripes,square,medium,stripes,cloud,dark,dots
14,jsh0wz9edlxszscd891dk534,5,False,True,cloud,medium,dots,square,medium,dots,star,medium,dots